### ISSUE TITLE
namelock plugin causes an exception if memory is empty

### ISSUE THREAD

**Issue by endofline** [nylonee/hangupsbot#35]
possibly missing a try block when the key doesnt exist

**Comment by nylonee** [comment]
I can't seem to replicate the issue, even after rm -rf-ing my memory.json file. Could you provide more details on this?

**Comment by endofline** [comment]
Try tailing the log, then renaming a test conversation. The exception is thrown at this point.

**Comment by endofline** [comment]
When I say renaming, rename any conversation that isn't name-locked using your own hangouts client (i.e. desktop, mobile)

**Comment by nylonee** [comment]
Fixed in commit https://github.com/nylonee/hangupsbot/commit/94869717b8e1ee165df11bd7d86ca1efcec0b02b

**Comment by endofline** [comment]
This still occurred on another bot, I suggest re-examining the exception and seeing whether it is indeed a TypeError or a KeyError
